Task_IdeaDesignGroup/Controllers/OrganizationController.cs
using DatabaseRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_IdeaDesignGroup.Models;
using Task_IdeaDesignGroup.ViewModel;
using Utility;

namespace Task_IdeaDesignGroup.Controllers
{
    public class OrganizationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrganizationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> OrganizationsList(string search, int page = 1, byte pageSize = 2)
        {
            if (page < 1)
                page = 1;

            List<OrganizationModel> model = new();
            IEnumerable<Organizations> organizations;

            if (!string.IsNullOrEmpty(search))
            {
                organizations = await _unitOfWork.Organizations.SearchOrganization(search);
            }
            else
            {
                organizations = _unitOfWork.Organizations.Get();
            }

            foreach (var organization in organizations)
            {
                var organizationMapped = ModelMapHandler.BuildModelMapping(organization, new OrganizationModel());
                model.Add(organizationMapped);
            }


            int organizationsCount = model.Count;
            int totalPages = 0;

            if (organizationsCount != 0)
                totalPages = organizationsCount % pageSize != 0 ? organizationsCount / pageSize + 1 : organizationsCount / pageSize;

            ViewBag.Page = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.SearchText = search;

            model = MyTools.Paging(model, page, pageSize).ToList();
            return View(model);
        }

        [HttpGet("CompanyDetails")]
        public async Task<IActionResult> OrganizationDetails(Guid id)
        {
            var persons = _unitOfWork.Organizations.GetPersonsInOrganization(id);
            var organization = GetOrganizationModel(id);
            if (organization is null)
            {
                return View("NotFound");
            }
            foreach (var person in await persons)
            {
                var mappedModel = ModelMapHandler.BuildModelMapping(person, new PersonModel());
                mappedModel.Gender = (Models.Gender?)person.GenderId;
                organization.Persons.Add(mappedModel);
            }
            return View(organization);
        }

        [HttpGet]
        public IActionResult AddOrEdit(Guid? id)
        {
            OrganizationModel model = new();

            if (id is null)
            {
                ViewBag.Title = "Add Organization";
                return View(model);
            }
            var organization = GetOrganizationModel(id.Value);
            if (organization is null)
            {
                return View("NotFound");
            }
            return View(organization);
        }

        [HttpPost]
        public IActionResult AddOrEdit(Guid? id, OrganizationModel model)
        {
            if (ModelState.IsValid)
            {
                var organization = ModelMapHandler.BuildModelMapping(model, new Organizations());
                if (id is null)
                {
                    _unitOfWork.Organizations.Insert(organization);
                }
                else
                {
                    organization.Id = model.Id;
                    _unitOfWork.Organizations.Update(organization);
                }
                return RedirectToAction("OrganizationsList");
            }
            return View(model);
        }

        public IActionResult Delete(Guid id)
        {
            var organization = _unitOfWork.Organizations.GetById(id);
            if (organization is null)
            {
                return View("NotFound");
            }
            _unitOfWork.Organizations.Delete(organization);
            return RedirectToAction("OrganizationsList");
        }

        [HttpGet("NewEmployee")]
        public async Task<IActionResult> AddEmployeeToOrganization(Guid organizationId)
        {
            var persons = _unitOfWork.Organizations.GetPersonsOutOfOrganization(organizationId);
            NewEmployeeViewModel model = new NewEmployeeViewModel() { OrganizationId = organizationId };
            foreach (var person in await persons)
            {
                var mappedModel = ModelMapHandler.BuildModelMapping(person, new PersonModel());
                mappedModel.Gender = (Models.Gender?)person.GenderId;
                model.Persons.Add(mappedModel);
            }
            return View(model);
        }

        [HttpPost("NewEmployee")]
        public IActionResult AddEmployeeToOrganization(Guid personId, Guid organizationId)
        {
            _unitOfWork.PersonToOrganizations.InsertPersonToOrganization(personId, organizationId);
            return RedirectToAction("AddEmployeeToOrganization", new { organizationId = organizationId });
        }
        public IActionResult RemoveEmployeeFromOrganization(Guid personId, Guid organizationId)
        {
            _unitOfWork.PersonToOrganizations.RemovePersonFromOrganization(personId, organizationId);
            return RedirectToAction("OrganizationDetails", new { id = organizationId });
        }
        private OrganizationModel GetOrganizationModel(Guid id)
        {
            var organization = _unitOfWork.Organizations.GetById(id);
            if (organization is not null)
            {
                var model = ModelMapHandler.BuildModelMapping(organization, new OrganizationModel());
                return model;
            }
            return null;
        }
    }
}

Task_IdeaDesignGroup/Controllers/PersonController.cs
using DatabaseRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task_IdeaDesignGroup.Models;
using Utility;

namespace Task_IdeaDesignGroup.Controllers
{
    public class PersonController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PersonController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> PersonsList(string search, int page = 1, byte pageSize = 2)
        {
            if (page < 1)
                page = 1;

            List<PersonModel> model = new();
            IEnumerable<Persons> persons;

            if (!string.IsNullOrEmpty(search))
            {
                persons = await _unitOfWork.Persons.SearchPerson(search);
            }
            else
            {
                persons = _unitOfWork.Persons.Get();
            }

            foreach (var person in persons)
            {
                var personMapped = ModelMapHandler.BuildModelMapping(person, new PersonModel());
                personMapped.Gender = (Models.Gender?)person.GenderId;
                model.Add(personMapped);
            }


            int personsCount = model.Count;
            int totalPages = 0;

            if (personsCount != 0)
                totalPages = personsCount % pageSize != 0 ? personsCount / pageSize + 1 : personsCount / pageSize;

            ViewBag.Page = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.SearchText = search;

            model = MyTools.Paging(model, page, pageSize).ToList();
            return View(model);
        }

        [HttpGet("Details")]
        public IActionResult PersonDetails(Guid id)
        {
            var person = GetPersonModel(id);
            if (person is null)
            {
                return View("NotFound");
            }
            return View(person);
        }

        [HttpGet]
        public IActionResult AddOrEdit(Guid? id)
        {
            PersonModel model = new();

            if (id is null)
            {
                ViewBag.Title = "Add Person";
                return View(model);
            }
            var person = GetPersonModel(id.Value);
            if (person is null)
            {
                return View("NotFound");
            }
            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(Guid? id, PersonModel model)
        {
            if (!await IsPersonalNumberInUse(model))
            {
                ModelState.AddModelError("", "Invalid Personal Id");
            }
            if (ModelState.IsValid)
            {
                Persons person = new Persons()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PersonalNumber = model.PersonalNumber,
                    GenderId = (byte)model.Gender.Value,
                    PhoneNumber = model.PhoneNumber,
                    City = model.City,
                    DateOfBirth = model.DateOfBirth.Value,
                    IsActive = model.IsActive
                };
                if (id is null)
                {
                    _unitOfWork.Persons.Insert(person);
                }
                else
                {
                    person.Id = model.Id;
                    _unitOfWork.Persons.Update(person);
                }
                return RedirectToAction("PersonsList");
            }
            return View(model);
        }

        public IActionResult Delete(Guid id)
        {
            var person = _unitOfWork.Persons.GetById(id);
            if (person is null)
            {
                return View("NotFound");
            }
            _unitOfWork.Persons.Delete(person);
            return RedirectToAction("PersonsList");
        }
        private PersonModel GetPersonModel(Guid id)
        {
            var person = _unitOfWork.Persons.GetById(id);
            if (person is not null)
            {
                var model = ModelMapHandler.BuildModelMapping(person, new PersonModel());
                model.Gender = (Models.Gender?)person.GenderId;
                return model;
            }
            return null;
        }

        private async Task<bool> IsPersonalNumberInUse(PersonModel model)
        {
            var person = await _unitOfWork.Persons.FindByPersonalNumberAsync(model.PersonalNumber);

            return person is null || person.Id == model.Id;
        }
    }
}

Task_IdeaDesignGroup/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>Page was not found</h1>

<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return</a>

Task_IdeaDesignGroup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task_IdeaDesignGroup</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonsList">Persons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organization" asp-action="OrganizationsList">Organizations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container"> 
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Task_IdeaDesignGroup - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>